<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use app\models\TestForm;


class PostController extends AppController
{
    private $posts = [
        [
            'id' => 1,
            'title' => 'Что лучше, это, или вот это?1',
            'text' => "lorem100..."
        ],
        [
            'id' => 2,
            'title' => 'Клара у Карла украла кораллы, а Карл у Клары украл кларнет',
            'text' => "Да, такая вот новость"
        ]
    ];

    public $layout = 'blog';


    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $this->enableCsrfValidation = true;

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return json_encode($this->posts);
        }

        $this->view->title = "Статьи";
        $this->view->registerMetaTag([
            'name' => 'keywords',
            'content' => 'статьи'
        ]);
        $this->view->registerMetaTag([
            'name' => 'description',
            'content' => 'Самые информативные статьи!..'
        ]);

        return $this->render('index', ['posts' => $this->posts]);
    }

    public function actionShow()
    {

    }

    public function actionForm()
    {
        $model = new TestForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                
            }
            else {

            }
        }

        return $this->render('form', compact('model'));
    }

    public function actionTest()
    {
//        $this->debug(Yii::$app);

        return $this->render('test');
    }
}